#include "stm32f4xx_hal.h"


#ifndef DEFINEINC_H_
#define DEFINEINC_H_

#define SET_A	GPIOB->BSRR |= GPIO_BSRR_BS1
#define RESET_A	GPIOB->BSRR |= GPIO_BSRR_BR1

#define SET_B	GPIOA->BSRR |= GPIO_BSRR_BS10
#define RESET_B	GPIOA->BSRR |= GPIO_BSRR_BR10

#define SET_C	GPIOC->BSRR |= GPIO_BSRR_BS7
#define RESET_C	GPIOC->BSRR |= GPIO_BSRR_BR7

#define SET_D	GPIOA->BSRR |= GPIO_BSRR_BS7
#define RESET_D	GPIOA->BSRR |= GPIO_BSRR_BR7

#define SET_E	GPIOA->BSRR |= GPIO_BSRR_BS6
#define RESET_E	GPIOA->BSRR |= GPIO_BSRR_BR6

#define SET_G	GPIOA->BSRR |= GPIO_BSRR_BS9
#define RESET_G	GPIOA->BSRR |= GPIO_BSRR_BR9

#define SET_F	GPIOB->BSRR |= GPIO_BSRR_BS15
#define RESET_F	GPIOB->BSRR |= GPIO_BSRR_BR15

#define SET_DP	GPIOB->BSRR |= GPIO_BSRR_BS6
#define RESET_DP	GPIOB->BSRR |= GPIO_BSRR_BR6

#define SET_D1	GPIOC->BSRR |= GPIO_BSRR_BS9
#define RESET_D1	GPIOC->BSRR |= GPIO_BSRR_BR9

#define SET_D2	GPIOB->BSRR |= GPIO_BSRR_BS9
#define RESET_D2	GPIOB->BSRR |= GPIO_BSRR_BR9

#define SET_D3	GPIOB->BSRR |= GPIO_BSRR_BS8
#define RESET_D3	GPIOB->BSRR |= GPIO_BSRR_BR8

#define SET_D4	GPIOB->BSRR |= GPIO_BSRR_BS2
#define RESET_D4	GPIOB->BSRR |= GPIO_BSRR_BR2

#define SET_D5	GPIOB->BSRR |= GPIO_BSRR_BS14
#define RESET_D5	GPIOB->BSRR |= GPIO_BSRR_BR14

#define SET_D6	GPIOB->BSRR |= GPIO_BSRR_BS13
#define RESET_D6	GPIOB->BSRR |= GPIO_BSRR_BR13


#endif /* DEFINEINC_H_ */
